# Generated by Django 3.0.3 on 2020-04-23 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SlNo', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=200)),
                ('Profession', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('Qualification', models.CharField(max_length=200)),
                ('EPICNo', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('FatherHusband', models.CharField(max_length=200)),
                ('Mobile', models.IntegerField()),
                ('Religion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('ShortName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(max_length=200)),
                ('Numbers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConstituencyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Telephone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Events123',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('SubmitDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('Description', models.CharField(max_length=200)),
                ('Place', models.CharField(max_length=200)),
                ('Time', models.TimeField()),
                ('Title', models.CharField(max_length=200)),
                ('Documents', models.FileField(blank=True, null=True, upload_to='Files/')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hobali',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.District')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('MiddleName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('Dob', models.DateField()),
                ('Mobile', models.IntegerField()),
                ('SpouseName', models.CharField(max_length=200)),
                ('Telephone', models.IntegerField()),
                ('Website', models.CharField(max_length=200)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='Photo/')),
                ('Constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Constituency')),
            ],
        ),
        migrations.CreateModel(
            name='MembersType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PartDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Number', models.IntegerField()),
                ('Circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Circle')),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.District')),
                ('Hobali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Hobali')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Description', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('ShortName', models.CharField(max_length=200)),
                ('SignName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Circle')),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.District')),
                ('Hobali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Hobali')),
            ],
        ),
        migrations.CreateModel(
            name='PressReporters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=200)),
                ('MediaName', models.CharField(max_length=200)),
                ('MediaType', models.CharField(max_length=200)),
                ('Reporter', models.CharField(max_length=200)),
                ('Mobile', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Website', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Taluka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citizen.District')),
                ('State', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citizen.State')),
            ],
        ),
        migrations.CreateModel(
            name='VillageCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Pincode', models.IntegerField()),
                ('Circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Circle')),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.District')),
                ('Hobali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Hobali')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.State')),
                ('Taluka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Taluka')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.IntegerField()),
                ('Telephone', models.IntegerField()),
                ('Constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Constituency')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Department')),
                ('Members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Members')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('Description', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('Year', models.DateField()),
                ('Constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Constituency')),
                ('Members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Members')),
            ],
        ),
        migrations.CreateModel(
            name='PressReporterConstituency123',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.BooleanField()),
                ('Constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Constituency')),
                ('PressReporters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.PressReporters')),
            ],
        ),
        migrations.CreateModel(
            name='PressReporterConstituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.BooleanField()),
                ('Constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Constituency')),
                ('PressReporters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.PressReporters')),
            ],
        ),
        migrations.CreateModel(
            name='PositionHeld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=200)),
                ('From', models.DateField()),
                ('To', models.DateField()),
                ('Members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Members')),
            ],
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Circle')),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.District')),
                ('Hobali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Hobali')),
                ('PartDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.PartDetails')),
                ('PoliceStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.PoliceStation')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.State')),
                ('Taluka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Taluka')),
                ('VillageCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.VillageCity')),
            ],
        ),
        migrations.AddField(
            model_name='policestation',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.State'),
        ),
        migrations.AddField(
            model_name='policestation',
            name='Taluka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Taluka'),
        ),
        migrations.AddField(
            model_name='policestation',
            name='VillageCity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.VillageCity'),
        ),
        migrations.CreateModel(
            name='PersonalAssistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='Photo/')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.IntegerField()),
                ('Status', models.BooleanField()),
                ('Telephone', models.IntegerField()),
                ('Members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Members')),
            ],
        ),
        migrations.CreateModel(
            name='PartyWorkers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.IntegerField()),
                ('Status', models.BooleanField(default=True)),
                ('Constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Constituency')),
                ('Members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Members')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Party')),
                ('PollingStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.PollingStation')),
            ],
        ),
        migrations.AddField(
            model_name='partdetails',
            name='PoliceStation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.PoliceStation'),
        ),
        migrations.AddField(
            model_name='partdetails',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.State'),
        ),
        migrations.AddField(
            model_name='partdetails',
            name='Taluka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Taluka'),
        ),
        migrations.AddField(
            model_name='partdetails',
            name='VillageCity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.VillageCity'),
        ),
        migrations.CreateModel(
            name='Officers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('From', models.DateField()),
                ('To', models.DateField()),
                ('Mobile', models.IntegerField()),
                ('Telephone', models.IntegerField()),
                ('Constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Constituency')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Department')),
                ('Members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Members')),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='MembersType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.MembersType'),
        ),
        migrations.CreateModel(
            name='MemberAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Pincode', models.CharField(max_length=200)),
                ('Members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Members')),
            ],
        ),
        migrations.AddField(
            model_name='hobali',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.State'),
        ),
        migrations.AddField(
            model_name='hobali',
            name='Taluka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Taluka'),
        ),
        migrations.CreateModel(
            name='Grievances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=200)),
                ('Place', models.CharField(max_length=200)),
                ('Remarks', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
                ('Documents', models.FileField(blank=True, null=True, upload_to='Files/')),
                ('Date', models.DateField()),
                ('Citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Citizen')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Department')),
                ('Members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Members')),
                ('Officers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Officers')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Citizen')),
                ('Family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.FamilyDetails')),
            ],
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='')),
                ('Title', models.CharField(max_length=200)),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Events123')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.State'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='ConstituencyType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citizen.ConstituencyType'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='District',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citizen.District'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='State',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citizen.State'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='Taluka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citizen.Taluka'),
        ),
        migrations.CreateModel(
            name='CommitteeMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Status', models.BooleanField()),
                ('Committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Committee')),
                ('CommitteeStructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.CommitteeStructure')),
                ('PartyWorkers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.PartyWorkers')),
            ],
        ),
        migrations.AddField(
            model_name='citizen',
            name='Address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.FamilyDetails'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='District',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='citizen.District'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='Hobali',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='citizen.Hobali'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='State',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citizen.State'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='Taluka',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='citizen.Taluka'),
        ),
        migrations.AddField(
            model_name='circle',
            name='District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.District'),
        ),
        migrations.AddField(
            model_name='circle',
            name='Hobali',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Hobali'),
        ),
        migrations.AddField(
            model_name='circle',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.State'),
        ),
        migrations.AddField(
            model_name='circle',
            name='Taluka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Taluka'),
        ),
    ]
