# Generated by Django 3.0.3 on 2020-05-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0003_members_constituencytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('SubmitDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('Description', models.CharField(max_length=200)),
                ('Place', models.CharField(max_length=200)),
                ('Time', models.TimeField()),
                ('Title', models.CharField(max_length=200)),
                ('Documents', models.FileField(blank=True, null=True, upload_to='Files/')),
            ],
        ),
    ]
