# Generated by Django 3.0.3 on 2020-05-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0005_projects_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Progressing', 'Progressing'), ('Sanctioned', 'Sanctioned')], max_length=20, null=True),
        ),
    ]
