# Generated by Django 3.0.3 on 2020-05-05 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0007_committeestructure123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee123',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('ShortName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMembers123',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Status', models.BooleanField()),
                ('Committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Committee123')),
                ('CommitteeStructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.CommitteeStructure123')),
                ('PartyWorkers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.PartyWorkers')),
            ],
        ),
    ]
