# Generated by Django 3.0.3 on 2020-05-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0008_committee123_committeemembers123'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee123',
            name='level',
            field=models.CharField(choices=[('N', 'National'), ('S', 'State'), ('D', 'District'), ('T', 'Taluka')], max_length=20, null=True),
        ),
    ]
