# Generated by Django 3.0.3 on 2020-05-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0009_committee123_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee123',
            name='level',
            field=models.CharField(choices=[('National', 'National'), ('State', 'State'), ('District', 'District'), ('Taluka', 'Taluka')], max_length=20, null=True),
        ),
    ]
