# Generated by Django 3.0.3 on 2020-05-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0010_auto_20200505_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemembers123',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
