# Generated by Django 3.0.3 on 2020-05-05 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0011_committeemembers123_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemembers123',
            name='PartyWorkers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='citizen.PartyWorkers'),
        ),
    ]
