# Generated by Django 3.0.3 on 2020-06-26 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0012_auto_20200505_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partyworkers',
            name='Party',
        ),
        migrations.AddField(
            model_name='partyworkers',
            name='Party123',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='citizen.Party123'),
        ),
    ]
