# Generated by Django 3.0.3 on 2020-05-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20200508_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='Description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
