# Generated by Django 3.0.3 on 2020-05-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_quiz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='SubmitDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
