# Generated by Django 3.0.3 on 2020-06-10 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0012_auto_20200505_1906'),
        ('classroom', '0006_quiz_submitdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=200)),
                ('SlNo', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=200)),
                ('Profession', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('Qualification', models.CharField(max_length=200)),
                ('EPICNo', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('FatherHusband', models.CharField(max_length=200)),
                ('Mobile', models.IntegerField()),
                ('Religion', models.CharField(max_length=200)),
                ('District', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='citizen.District')),
                ('Hobali', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='citizen.Hobali')),
                ('State', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citizen.State')),
                ('Taluka', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='citizen.Taluka')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
